[package]
name = "anon_holder_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
ethers-core = "2.0.14"
risc0-zkvm = { version = "^3.0.5", default-features = false, features = ['std'] }
